### ISSUE TITLE
wrong file extension for config?

### ISSUE THREAD

**Issue by ToadRage** [dotcomboom/mkwii-rpredux#2]
Is it possible you want .xml instead of .config?

**Comment by dotcomboom** [comment]
I used .NET Framework's own Settings stuff; the .config extensions are just its practice, even though it's an XML-based format. If it works, it works :-)

More details here if you are curious.. [https://learn.microsoft.com/en-us/visualstudio/ide/managing-application-settings-dotnet?view=vs-2022&source=recommendations#access-or-change-application-settings-at-runtime-in-visual-basic](https://learn.microsoft.com/en-us/visualstudio/ide/managing-application-settings-dotnet?view=vs-2022&source=recommendations#access-or-change-application-settings-at-runtime-in-visual-basic)

> When you create an application-scoped setting (for example, a database connection string, or a reference to server resources), Visual Studio saves it in app.config file with the <applicationSettings> tag. (Connection strings are saved under the <connectionStrings> tag.)
> When you create a user-scoped setting (for example, default font, home page, or window size), Visual Studio saves it in app.config file with the <userSettings> tag.
> ...
> The values of any user-scoped settings that the user changes at runtime (for example, the position of a form) are stored in a user.config file. Notice that the default values are still saved in app.config.
